### ISSUE TITLE
Bug: Bei Sensitivität = 100% wird Wahrscheinlichkeit = "Infinity %" angezeigt.

### ISSUE THREAD

**Issue by camagda** [jzakotnik/wirklichpositiv#3]
Erwarteter Wert: Wahrscheinlichkeit = 100%.
Aktuell testbar mit Hersteller "Triplex".

**Comment by jzakotnik** [comment]
Das stimmt, da scheint ein Fehler in der Berechnung. Aber verstehe es auch in dem ursprünglichen RKI Post nicht.

**Comment by jzakotnik** [comment]
Danke! Das war tatsächlich ein Fehler in der Berechnung, der Nenner muss natürlich die Summe enthalten.
